### ISSUE TITLE
Eccezioni non gestite in Favorites

### ISSUE THREAD

**Issue by PasqualeMuraca** [Pasqualecoder/FratelliMuraca#3]
Caro @GiuseppePastena23,
vorrei tanto non guardare più quella [riga](https://github.com/Pasqualecoder/FratelliMuraca/blame/6b1d37a9b1b9e5e96cff54746133dbc7cd4cfa38/FratelliMuraca/src/controlUser/FavoriteControl.java#L54) che da questo pomeriggio mi attanaglia
`id = String.valueOf(((favoriteModel.doRetrieveFavorite(user.getId(), Integer.parseInt(request.getParameter("id")))).getId())); // PASQUALE NON GUARDARE`

tuttavia non posso ignorare l'eccezione che viene sollevata **sempre** all'esecuzione della Servlet. Ecco a te parte dello stack trace:
```
java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:614)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at controlUser.FavoriteControl.doGet(FavoriteControl.java:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at filter.UserFilter.doFilter(UserFilter.java:65)
```
Poiché il mio dispositivo intracranico Neuralink è attualmente in fase di update non sono in grado di convertire questa riga, che sembra tendente all'Assembly, in logica comprensibile a un non calcolatore.
Mi tormenta quindi la seguente domanda: se l'id è sempre null cosa viene fatto dopo questo tentativo di assegnazione?

Sempre per quanto riguarda i Favorites,
l'interfaccia grafica consente di aggiungere ai preferiti un prodotto già preferito (in DetailsView.jsp non viene effettuato nessun controllo se l'utente ha già nei preferiti questo prodotto). Quando si verifica questo evento MySQL da l'errore `java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '11-2' for key 'preferiti.id_cliente'` dove 11 è l'id del cliente e 2 l'id del prodotto. Premettendo che è un errore di cui sono contento perché il db funziona bene però sarebbe opportuno
- impedire all'utente di sollevare questa eccezione così facilmente aggiungendo un controllo nel frontend passando dal backend un attributo (così scegli se colorare anticipatamente il cuore oppure no) 
(
se il prodotto è gia preferito: cuore colorato e se premuto cancella il preferito
se non è preferito: cuore non colorato e se premuto aggiunge il preferito
)

oppure
- nel model effettuare il controllo dell'esistenza della tupla e non inserirla.

Confido in una tua brillante soluzione 💪🚀

Cordiali Saluti,
Pasku♥

**Comment by GiuseppePastena23** [comment]
Caro @Pasqualecoder 
il problema e' stato risolto Grazie per il tuo lavoro overtime
